"use client";

import Link from "next/link";
import { Sparkles, Unlock } from "lucide-react";
import MediaPreview from "@/components/MediaPreview";
import CopyPromptButton from "@/components/CopyPromptButton";
import { formatUsdc, type PublicCatalogEntry } from "@/lib/api";

/**
 * One gallery card: inline preview, title, category, and the entry's
 * action row.
 *
 * The design review's finding is load-bearing here: the copy control,
 * price badge, and unlock control are ALWAYS in the layout — never
 * revealed on hover. Hover-reveal hides actions from keyboard, touch,
 * and assistive-tech users alike; a permanently visible action row plus
 * per-control `:focus-visible` rings and entry-specific accessible names
 * satisfies all four at once.
 */
export default function PromptCard({ entry }: { entry: PublicCatalogEntry }) {
  const paid = entry.tier === "paid";

  return (
    <article
      aria-label={`${entry.title} — ${entry.category}`}
      className="group flex flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white transition-shadow focus-within:shadow-md hover:shadow-md"
    >
      <MediaPreview entry={entry} className="aspect-video" />

      <div className="flex flex-1 flex-col gap-3 p-4">
        <div className="flex items-start justify-between gap-3">
          <h3 className="text-sm font-semibold text-black">
            <Link
              href={`/prompts/${entry.id}`}
              className="rounded transition-colors hover:text-gray-600 focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 focus-visible:outline-none"
            >
              {entry.title}
            </Link>
          </h3>
          <span className="shrink-0 rounded-full border border-gray-200 px-2.5 py-0.5 text-[11px] font-medium text-gray-600">
            {entry.category}
          </span>
        </div>

        {paid && (
          <p className="flex items-center gap-1.5 text-[11px] text-gray-500">
            <Sparkles aria-hidden className="h-3 w-3" />
            Preview generated by running this exact prompt
          </p>
        )}

        <div className="mt-auto flex items-center justify-between gap-3">
          {paid ? (
            <>
              <span
                aria-label={`Price: ${formatUsdc(entry.priceAtomic)} in USDC`}
                className="rounded-full bg-black px-2.5 py-1 text-xs font-semibold text-white"
              >
                {formatUsdc(entry.priceAtomic)}
              </span>
              <Link
                href={`/prompts/${entry.id}`}
                aria-label={`Unlock ${entry.title} for ${formatUsdc(entry.priceAtomic)} in USDC`}
                className="inline-flex items-center gap-1.5 rounded-full border border-gray-300 px-4 py-2 text-xs font-medium text-black transition-colors hover:border-black focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 focus-visible:outline-none"
              >
                <Unlock aria-hidden className="h-3.5 w-3.5" />
                Unlock
              </Link>
            </>
          ) : (
            <>
              <span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-600">
                Free
              </span>
              <CopyPromptButton promptId={entry.id} title={entry.title} />
            </>
          )}
        </div>
      </div>
    </article>
  );
}
