import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import PromptDetailPage from "@/app/prompts/[id]/page";
import Providers from "@/app/providers";
import {
  freeVideoEntry,
  paidEntry,
  stubCatalogFetch,
  stubIntersectionObserver,
  stubMatchMedia,
  stubMediaElement,
} from "./helpers";

// The page reads its id from next/navigation's useParams; drive it per test.
const currentParams = { id: "test-prompt" };
vi.mock("next/navigation", () => ({
  useParams: () => currentParams,
}));

// Providers imports @/lib/appkit for its side effect (createAppKit). jsdom
// is not a browser AppKit can drive, and its init fetches remote config that
// this suite's fetch stubs would garble — so the init module and the one
// AppKit hook WalletButton reads are stubbed. The REAL wagmi provider
// machinery below stays live, which is the point of this suite.
vi.mock("@/lib/appkit", () => ({}));
vi.mock("@reown/appkit/react", () => ({
  useAppKit: () => ({ open: vi.fn() }),
}));

// U6's unlock control lives on this page and calls wagmi hooks, so the page
// renders under the real app providers (wagmi + query). jsdom has no injected
// wallet, which is exactly the disconnected state the paid test asserts.
function renderPage() {
  return render(
    <Providers>
      <PromptDetailPage />
    </Providers>,
  );
}

beforeEach(() => {
  stubMediaElement();
  stubIntersectionObserver();
  stubMatchMedia(true);
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("prompt detail", () => {
  it("renders a not-found state for an unknown id", async () => {
    currentParams.id = "does-not-exist";
    stubCatalogFetch([freeVideoEntry]);
    renderPage();

    expect(
      await screen.findByRole("heading", { name: "Prompt not found" }),
    ).toBeTruthy();
    // The dead end offers a way back to the gallery.
    expect(screen.getByRole("link", { name: "Browse the gallery" })).toBeTruthy();
  });

  it("renders the entry with attribution and copy control for a free prompt", async () => {
    currentParams.id = freeVideoEntry.id;
    stubCatalogFetch([freeVideoEntry]);
    renderPage();

    expect(
      await screen.findByRole("heading", { name: freeVideoEntry.title }),
    ).toBeTruthy();
    expect(screen.getByText(freeVideoEntry.attribution.note)).toBeTruthy();
    expect(
      screen.getByRole("button", {
        name: `Copy the full prompt text of ${freeVideoEntry.title}`,
      }),
    ).toBeTruthy();
  });

  it("renders price, unlock control, and the output claim for a paid prompt", async () => {
    currentParams.id = paidEntry.id;
    stubCatalogFetch([paidEntry]);
    renderPage();

    expect(await screen.findByRole("heading", { name: paidEntry.title })).toBeTruthy();
    expect(screen.getByLabelText("Price: $0.50 in USDC")).toBeTruthy();
    // No wallet in jsdom: the unlock control prompts connection, not an error.
    expect(screen.getByRole("button", { name: /connect wallet/i })).toBeTruthy();
    expect(
      screen.getByText(`Connect a browser wallet to unlock this prompt for $0.50.`),
    ).toBeTruthy();
    expect(screen.getByText(/generated by running this\s+exact prompt/)).toBeTruthy();
    // The signature-not-transaction story is visible before any wallet UI (U6).
    expect(screen.getByText(/not a transaction/)).toBeTruthy();
  });

  it("renders an error state with a way back when the API is unreachable", async () => {
    currentParams.id = freeVideoEntry.id;
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new TypeError("network down")));
    renderPage();

    const alert = await screen.findByRole("alert");
    // Scoped: the page header carries its own "Back to gallery" link too.
    expect(within(alert).getByRole("link", { name: "Back to gallery" })).toBeTruthy();
  });
});
