import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import PromptCard from "@/components/PromptCard";
import {
  freeVideoEntry,
  paidEntry,
  stubCatalogFetch,
  stubClipboard,
  stubIntersectionObserver,
  stubMatchMedia,
  stubMediaElement,
} from "./helpers";

beforeEach(() => {
  stubMediaElement();
  stubIntersectionObserver();
  stubMatchMedia(true); // hold posters; playback has its own suite
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("free card copy control", () => {
  it("puts the full prompt text on the clipboard and confirms", async () => {
    const body = "Full prompt body,\nmany lines long.";
    stubCatalogFetch([freeVideoEntry], { [freeVideoEntry.id]: body });
    const writeText = stubClipboard();
    render(<PromptCard entry={freeVideoEntry} />);

    fireEvent.click(
      screen.getByRole("button", {
        name: `Copy the full prompt text of ${freeVideoEntry.title}`,
      }),
    );

    await waitFor(() => expect(writeText).toHaveBeenCalledWith(body));
    // Visible confirmation…
    expect(screen.getByText("Copied!")).toBeTruthy();
    // …and the same confirmation announced to assistive technology.
    const status = screen
      .getAllByRole("status")
      .find((el) => el.getAttribute("aria-live") === "polite");
    expect(status?.textContent).toContain("copied to clipboard");
  });

  it("names the failure and offers a retry when the text fetch fails", async () => {
    stubCatalogFetch([freeVideoEntry], {}); // no body registered -> 404
    stubClipboard();
    render(<PromptCard entry={freeVideoEntry} />);

    fireEvent.click(screen.getByRole("button", { name: /Copy the full prompt text/ }));
    expect(await screen.findByText("Copy failed — retry")).toBeTruthy();
  });
});

describe("paid card", () => {
  it("shows price, unlock control, and the preview-is-this-prompt's-output claim", () => {
    stubCatalogFetch([paidEntry]);
    render(<PromptCard entry={paidEntry} />);

    expect(screen.getByLabelText("Price: $0.50 in USDC")).toBeTruthy();
    expect(
      screen.getByRole("link", {
        name: `Unlock ${paidEntry.title} for $0.50 in USDC`,
      }),
    ).toBeTruthy();
    expect(
      screen.getByText("Preview generated by running this exact prompt"),
    ).toBeTruthy();
  });
});

describe("controls are discoverable without a pointer (design-review finding)", () => {
  /**
   * Hover-reveal was rejected: the action row must be in the layout and the
   * accessibility tree unconditionally, so keyboard focus reaches controls
   * that are already visible — not ones a :hover rule would later unhide.
   */
  function expectAlwaysVisible(el: HTMLElement) {
    // In the accessibility tree: never aria-hidden, never focus-trapped out.
    expect(el.closest("[aria-hidden='true']")).toBeNull();
    expect(el.getAttribute("tabindex")).not.toBe("-1");
    // Not styled as a hover-reveal: no opacity-0 / hidden / invisible class
    // anywhere between the control and the card root.
    for (let node = el as HTMLElement | null; node; node = node.parentElement) {
      const cls = node.className ?? "";
      expect(cls, `${node.tagName} hides the control until hover`).not.toMatch(
        /(?:^|\s)(opacity-0|hidden|invisible|sr-only)(?:\s|$)/,
      );
      if (node.tagName === "ARTICLE") break;
    }
    // Keyboard users get a visible focus indicator.
    expect(el.className).toContain("focus-visible:ring");
  }

  it("free card: the copy control is permanently visible and named", () => {
    stubCatalogFetch([freeVideoEntry]);
    render(<PromptCard entry={freeVideoEntry} />);
    expectAlwaysVisible(
      screen.getByRole("button", {
        name: `Copy the full prompt text of ${freeVideoEntry.title}`,
      }),
    );
  });

  it("paid card: price badge and unlock control are permanently visible and named", () => {
    stubCatalogFetch([paidEntry]);
    render(<PromptCard entry={paidEntry} />);
    const price = screen.getByLabelText("Price: $0.50 in USDC");
    expect(price.closest("[aria-hidden='true']")).toBeNull();
    expect(price.className).not.toMatch(/(?:^|\s)opacity-0(?:\s|$)/);
    expectAlwaysVisible(
      screen.getByRole("link", {
        name: `Unlock ${paidEntry.title} for $0.50 in USDC`,
      }),
    );
  });
});
