"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { CheckCircle2, PenLine, Sparkles, UploadCloud } from "lucide-react";
import Nav from "@/components/Nav";
import { CATEGORIES, formatUsdc, type Category, type PublicCatalogEntry } from "@/lib/api";
import {
  ACCEPTED_MEDIA_TYPES,
  ListingApiError,
  canonicalListingMessage,
  connectWallet,
  fetchListingBounds,
  getInjectedProvider,
  prepareListing,
  randomListingNonce,
  signListingMessage,
  submitListing,
  usdcToAtomic,
  type ListingBounds,
} from "@/lib/listing";

/**
 * Form creator listing (U7). Setiap state bernama (R27):
 * idle → preparing (hash server-side) → signing (personal_sign EIP-191)
 * → uploading (progress %) → success | error.
 *
 * Jalur error MEMPERTAHANKAN semua nilai field dan menawarkan retry —
 * kreator yang kehilangan prompt panjang karena upload putus tidak akan
 * kembali. Nilai hanya di-reset lewat "List another prompt" setelah sukses.
 *
 * Preview boleh berupa upload ATAU link. R5 tidak melarang kreator
 * menempelkan URL — yang dilarang adalah katalog menyimpan alamat pihak
 * ketiga, karena pemiliknya bisa mengganti isinya setelah pembeli membayar
 * untuk melihatnya. Link diunduh dan disalin server saat listing dibuat,
 * jadi galeri tetap hanya menyajikan byte milik Promit. File menang kalau
 * keduanya terisi. Checkbox atestasi menegakkan R24 di sisi form — katalog
 * akan menyatakan bahwa preview adalah output prompt ini.
 */

type SubmitPhase =
  | { kind: "idle" }
  | { kind: "preparing" }
  | { kind: "signing" }
  | { kind: "uploading"; progress: number }
  | { kind: "success"; entry: PublicCatalogEntry }
  | { kind: "error"; message: string; fields?: Record<string, string> };

type BoundsState =
  | { kind: "pending" }
  | { kind: "ready"; bounds: ListingBounds }
  | { kind: "error" };

const inputClass =
  "rounded-xl border border-gray-300 px-3.5 py-2.5 text-sm text-black placeholder:text-gray-400 focus-visible:ring-2 focus-visible:ring-black focus-visible:outline-none disabled:bg-gray-50 disabled:text-gray-500";

export default function ListPromptPage() {
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState<Category | "">("");
  const [body, setBody] = useState("");
  const [price, setPrice] = useState("");
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  // A link is an alternative to the file, never an addition: the server
  // mirrors it, so both paths end as bytes Prom It owns.
  const [mediaLink, setMediaLink] = useState("");
  const [previewAttested, setPreviewAttested] = useState(false);
  const [phase, setPhase] = useState<SubmitPhase>({ kind: "idle" });
  const [boundsState, setBoundsState] = useState<BoundsState>({ kind: "pending" });
  const [connectedAddress, setConnectedAddress] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    let cancelled = false;
    fetchListingBounds()
      .then((bounds) => {
        if (!cancelled) setBoundsState({ kind: "ready", bounds });
      })
      .catch(() => {
        if (!cancelled) setBoundsState({ kind: "error" });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const submitting =
    phase.kind === "preparing" || phase.kind === "signing" || phase.kind === "uploading";
  const fieldErrors = phase.kind === "error" ? (phase.fields ?? {}) : {};
  const errorFor = (...names: string[]) => {
    for (const name of names) {
      if (fieldErrors[name]) return fieldErrors[name];
    }
    return null;
  };

  function clientFieldErrors(): Record<string, string> {
    const fields: Record<string, string> = {};
    if (!title.trim()) fields.title = "Title is required.";
    if (!category) fields.category = "Pick a category.";
    if (!body.trim()) fields.body = "Prompt body is required.";
    const atomic = usdcToAtomic(price);
    if (!atomic) {
      fields.price = "Enter a USDC price like 0.50 (up to 6 decimals).";
    } else if (boundsState.kind === "ready") {
      const { minPriceAtomic, maxPriceAtomic } = boundsState.bounds;
      if (BigInt(atomic) < BigInt(minPriceAtomic) || BigInt(atomic) > BigInt(maxPriceAtomic)) {
        fields.price = `Price must be between ${formatUsdc(minPriceAtomic)} and ${formatUsdc(maxPriceAtomic)}.`;
      }
    }
    if (!mediaFile && mediaLink.trim() === "")
      fields.media = "Upload the preview generated by running this prompt, or paste a link to it.";
    if (!previewAttested) {
      fields.attestation = "Confirm the preview is this exact prompt's own output.";
    }
    return fields;
  }

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    if (submitting) return;

    const clientErrors = clientFieldErrors();
    if (Object.keys(clientErrors).length > 0) {
      setPhase({
        kind: "error",
        message: "Fix the highlighted fields, then try again.",
        fields: clientErrors,
      });
      return;
    }

    const provider = getInjectedProvider();
    if (!provider) {
      setPhase({
        kind: "error",
        message:
          "No browser wallet was found. Install one (for example MetaMask) — " +
          "your wallet is your creator identity, and listing requires its signature.",
      });
      return;
    }

    const priceAtomic = usdcToAtomic(price)!;
    try {
      setPhase({ kind: "preparing" });
      const { contentHash } = await prepareListing(body);

      setPhase({ kind: "signing" });
      const address = connectedAddress ?? (await connectWallet(provider));
      setConnectedAddress(address);
      const nonce = randomListingNonce();
      const signature = await signListingMessage(
        provider,
        address,
        canonicalListingMessage({ title, category, contentHash, priceAtomic, nonce }),
      );

      setPhase({ kind: "uploading", progress: 0 });
      const form = new FormData();
      form.set("title", title);
      form.set("category", category);
      form.set("body", body);
      form.set("priceAtomic", priceAtomic);
      form.set("nonce", nonce);
      form.set("creatorAddress", address);
      form.set("signature", signature);
      // The file wins when both are present; a creator who picked a file
      // after typing a link meant the file.
      if (mediaFile) form.set("media", mediaFile);
      else form.set("media", mediaLink.trim());
      const entry = await submitListing(form, (progress) =>
        setPhase({ kind: "uploading", progress }),
      );
      setPhase({ kind: "success", entry });
    } catch (error) {
      // Nilai field TIDAK disentuh: state error hanya mengganti fase, jadi
      // retry melanjutkan dari isian yang sama.
      if (error instanceof ListingApiError) {
        setPhase({ kind: "error", message: error.message, fields: error.fields });
      } else {
        const message =
          error instanceof Error && /reject|denied/i.test(error.message)
            ? "The wallet rejected the signature. Nothing was sent — try again when ready."
            : "Something interrupted the submission. Your entries are kept — try again.";
        setPhase({ kind: "error", message });
      }
    }
  }

  function resetForm() {
    setTitle("");
    setCategory("");
    setBody("");
    setPrice("");
    setMediaFile(null);
    setMediaLink("");
    setPreviewAttested(false);
    setPhase({ kind: "idle" });
    if (fileInputRef.current) fileInputRef.current.value = "";
  }

  const busyLabel =
    phase.kind === "preparing"
      ? "Preparing listing…"
      : phase.kind === "signing"
        ? "Waiting for wallet signature…"
        : phase.kind === "uploading"
          ? `Uploading… ${phase.progress}%`
          : null;

  return (
    <div className="min-h-screen bg-white">
      <Nav />

      <main className="mx-auto max-w-3xl px-4 pt-8 pb-24 sm:px-6">
        <h1 className="mb-2 flex items-center gap-2 text-3xl font-normal tracking-tight">
          <PenLine aria-hidden className="h-6 w-6" />
          List your prompt
        </h1>
        <p className="mb-1 text-sm text-gray-600">
          Sell a prompt you wrote. Listing signs a message with your wallet —
          not a transaction. No gas needed, and the wallet address is your
          creator identity.
        </p>
        <p className="mb-8 text-xs text-gray-500">
          {boundsState.kind === "ready" && (
            <>
              Published price bounds:{" "}
              {formatUsdc(boundsState.bounds.minPriceAtomic)}–
              {formatUsdc(boundsState.bounds.maxPriceAtomic)} USDC per unlock.
            </>
          )}
          {boundsState.kind === "pending" && "Loading published price bounds…"}
          {boundsState.kind === "error" &&
            "Price bounds couldn't load — the server still enforces them on submit."}
        </p>

        {phase.kind === "success" ? (
          <div
            role="status"
            className="rounded-2xl border border-gray-200 px-6 py-16 text-center"
          >
            <CheckCircle2 aria-hidden className="mx-auto mb-4 h-10 w-10 text-black" />
            <h2 className="mb-2 text-2xl font-normal tracking-tight">
              “{phase.entry.title}” is live
            </h2>
            <p className="mb-6 text-sm text-gray-600">
              Your prompt is listed at {formatUsdc(phase.entry.priceAtomic)} per
              unlock. Buyers can verify its content hash independently.
            </p>
            <div className="flex items-center justify-center gap-3">
              <Link
                href={`/prompts/${phase.entry.id}`}
                className="rounded-full bg-black px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-gray-800 focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 focus-visible:outline-none"
              >
                View your listing
              </Link>
              <button
                type="button"
                onClick={resetForm}
                className="rounded-full border border-gray-300 px-5 py-2.5 text-sm font-medium text-black transition-colors hover:border-black focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 focus-visible:outline-none"
              >
                List another prompt
              </button>
            </div>
          </div>
        ) : (
          <form onSubmit={handleSubmit} aria-busy={submitting} noValidate>
            {phase.kind === "error" && (
              <div
                role="alert"
                className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"
              >
                {phase.message}
              </div>
            )}

            <div className="flex flex-col gap-5">
              <label className="flex flex-col gap-1.5">
                <span className="text-sm font-medium text-black">Title</span>
                <input
                  type="text"
                  name="title"
                  value={title}
                  maxLength={120}
                  onChange={(e) => setTitle(e.target.value)}
                  disabled={submitting}
                  placeholder="Neon night-market signup flow"
                  className={inputClass}
                />
                {errorFor("title") && (
                  <span className="text-xs text-red-700">{errorFor("title")}</span>
                )}
              </label>

              <label className="flex flex-col gap-1.5">
                <span className="text-sm font-medium text-black">Category</span>
                <select
                  name="category"
                  value={category}
                  onChange={(e) => setCategory(e.target.value as Category)}
                  disabled={submitting}
                  className={inputClass}
                >
                  <option value="" disabled>
                    Choose a category
                  </option>
                  {CATEGORIES.map((name) => (
                    <option key={name} value={name}>
                      {name}
                    </option>
                  ))}
                </select>
                {errorFor("category") && (
                  <span className="text-xs text-red-700">{errorFor("category")}</span>
                )}
              </label>

              <label className="flex flex-col gap-1.5">
                <span className="text-sm font-medium text-black">Prompt body</span>
                <span className="text-xs text-gray-500">
                  The full text buyers unlock. It is hashed with the published
                  rule so buyers can verify delivery byte-for-byte; it never
                  appears publicly.
                </span>
                <textarea
                  name="body"
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  disabled={submitting}
                  rows={10}
                  placeholder="Design a neon-lit signup flow for a night-market app…"
                  className={`${inputClass} resize-y font-mono text-xs leading-relaxed`}
                />
                {errorFor("body") && (
                  <span className="text-xs text-red-700">{errorFor("body")}</span>
                )}
              </label>

              <div className="flex flex-col gap-1.5">
                <label className="flex flex-col gap-1.5">
                  <span className="flex items-center gap-1.5 text-sm font-medium text-black">
                    <Sparkles aria-hidden className="h-4 w-4" />
                    Preview — the output of running this prompt
                  </span>
                  <span className="text-xs text-gray-500">
                    Run the prompt, capture the result as an image or short
                    clip, and upload the file. Links aren&apos;t accepted:
                    previews are served from Promit-owned storage only, so a
                    URL can&apos;t change under a buyer after they paid.
                  </span>
                  {/* The limits the server enforces, said before the upload
                      rather than after it. A rejection that only arrives on
                      submit costs the creator the whole form. */}
                  <span className="text-xs text-gray-500">
                    PNG, JPEG, WebP, MP4 or WebM, up to 10 MB. Short clips
                    compress well: ten seconds of H.264 is usually under 300 KB.
                  </span>
                  <input
                    ref={fileInputRef}
                    type="file"
                    name="media"
                    accept={ACCEPTED_MEDIA_TYPES}
                    onChange={(e) => setMediaFile(e.target.files?.[0] ?? null)}
                    disabled={submitting}
                    aria-label="Preview media file"
                    className="text-sm text-gray-600 file:mr-3 file:rounded-full file:border-0 file:bg-black file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-gray-800"
                  />
                </label>
                {mediaFile && (
                  <span className="flex items-center gap-1.5 text-xs text-gray-600">
                    <UploadCloud aria-hidden className="h-3.5 w-3.5" />
                    {mediaFile.name} · {Math.max(1, Math.round(mediaFile.size / 1024))} KB
                  </span>
                )}
                <div className="mt-3">
                  <label
                    htmlFor="mediaLink"
                    className="mb-1 block text-xs font-medium text-gray-700"
                  >
                    Or paste a link to it
                  </label>
                  <input
                    id="mediaLink"
                    type="url"
                    inputMode="url"
                    value={mediaLink}
                    onChange={(e) => setMediaLink(e.target.value)}
                    disabled={mediaFile !== null}
                    placeholder="https://example.com/preview.mp4"
                    className="w-full rounded-xl border border-gray-300 px-3 py-2 text-sm placeholder:text-gray-400 focus-visible:ring-2 focus-visible:ring-black focus-visible:outline-none disabled:bg-gray-50 disabled:text-gray-400"
                  />
                  <span className="mt-1 block text-xs text-gray-500">
                    Prom It downloads it once and serves its own copy, so the
                    preview can&apos;t change after someone pays to see it.
                  </span>
                </div>

                {/* Shown from the creator's own browser, so a broken link is
                    obvious before signing rather than after the server has
                    already refused it. */}
                {!mediaFile && /^https?:\/\/\S+$/.test(mediaLink.trim()) && (
                  <div className="mt-3 overflow-hidden rounded-xl border border-gray-200">
                    {/* eslint-disable-next-line @next/next/no-img-element -- arbitrary creator URL, no loader */}
                    <img
                      src={mediaLink.trim()}
                      alt="Preview of the link you pasted"
                      className="max-h-56 w-full object-contain"
                      onError={(e) => {
                        (e.currentTarget as HTMLImageElement).style.display = "none";
                      }}
                    />
                  </div>
                )}

                {errorFor("media") && (
                  <span className="text-xs text-red-700">{errorFor("media")}</span>
                )}
                <label className="mt-1 flex items-start gap-2 text-xs text-gray-600">
                  <input
                    type="checkbox"
                    checked={previewAttested}
                    onChange={(e) => setPreviewAttested(e.target.checked)}
                    disabled={submitting}
                    className="mt-0.5 h-4 w-4 rounded border-gray-300 accent-black"
                  />
                  <span>
                    This preview was generated by running this exact prompt.
                    The catalog states this claim next to your listing.
                  </span>
                </label>
                {errorFor("attestation") && (
                  <span className="text-xs text-red-700">{errorFor("attestation")}</span>
                )}
              </div>

              <label className="flex flex-col gap-1.5">
                <span className="text-sm font-medium text-black">Price per unlock (USDC)</span>
                <input
                  type="text"
                  name="price"
                  inputMode="decimal"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  disabled={submitting}
                  placeholder="0.25"
                  className={`${inputClass} max-w-40`}
                />
                {errorFor("price", "priceAtomic") && (
                  <span className="text-xs text-red-700">
                    {errorFor("price", "priceAtomic")}
                  </span>
                )}
              </label>

              {connectedAddress && (
                <p className="text-xs text-gray-500">
                  Creator wallet:{" "}
                  <span className="font-mono" title={connectedAddress}>
                    {connectedAddress.slice(0, 6)}…{connectedAddress.slice(-4)}
                  </span>
                </p>
              )}

              {phase.kind === "uploading" && (
                <div className="flex flex-col gap-1.5">
                  <div
                    role="progressbar"
                    aria-valuenow={phase.progress}
                    aria-valuemin={0}
                    aria-valuemax={100}
                    aria-label="Upload progress"
                    className="h-2 overflow-hidden rounded-full bg-gray-100"
                  >
                    <div
                      className="h-full rounded-full bg-black transition-[width]"
                      style={{ width: `${phase.progress}%` }}
                    />
                  </div>
                  <span aria-live="polite" className="text-xs text-gray-600">
                    Uploading preview… {phase.progress}%
                  </span>
                </div>
              )}

              <button
                type="submit"
                disabled={submitting}
                className="inline-flex w-fit items-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-gray-800 focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:bg-gray-400"
              >
                {busyLabel ?? (phase.kind === "error" ? "Try again" : "Sign & list prompt")}
              </button>
            </div>
          </form>
        )}
      </main>
    </div>
  );
}
